name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: pip install -U "jupyterlab>=4.0.0,<5" build

      - name: Install JS dependencies
        run: npm install
      
      - name: Lint the extension
        run: npm run eslint:check

      - name: Build JS packages
        run: npm run build:prod

      - name: Build Python package
        run: python -m build

      - name: Upload extension packages
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: |
            dist/*.whl

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1